package works.bosk.bytecode;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;

import static java.util.Objects.requireNonNull;

/**
 * Runtime support for classes generated by {@link GeneratedClass}.
 * <p>
 * The classes {@link GeneratedClass} generates capture the objects they need
 * (their <em>curried values</em>) in static final fields. Because those values
 * are arbitrary runtime objects that can't be embedded in the classfile as
 * constants, {@link GeneratedClass} registers them here and the generated class's
 * static initializer claims them by key and stores them in its fields.
 * <p>
 * This class must be public because it is referenced from generated bytecode,
 * which is loaded by a different classloader.
 */
public final class BytecodeRuntime {
	private static final AtomicLong curriedArrayCounter = new AtomicLong(0);
	private static final Map<Long, Object[]> curriedArrays = new HashMap<>();

	/**
	 * Registers the given objects for later claim by a generated class's static initializer.
	 *
	 * @return the key the generated class should use to {@link #claimCurriedArray claim} them.
	 */
	static long curry(Object[] objects) {
		long key = curriedArrayCounter.incrementAndGet();
		synchronized (curriedArrays) {
			curriedArrays.put(key, objects);
		}
		return key;
	}

	/**
	 * Removes and returns the curried values registered under the given key.
	 * Claiming removes the entry, so a generated class holds the only reference.
	 */
	@SuppressWarnings("unused") // Called from generated bytecode
	public static Object[] claimCurriedArray(long key) {
		Object[] objects;
		synchronized (curriedArrays) {
			objects = curriedArrays.remove(key);
		}
		return requireNonNull(objects);
	}

	private BytecodeRuntime() {}
}
